






#define ID_INPUTVIEW_WND				81211

#define	ID_SYNTAXPANE_WND				81212



#define ID_DOC_PARSETAG_TIMER	(WM_USER + 101)
#define ID_EDIT_LOCATE_POS		(WM_USER + 102)
#define ID_INPUT_LOCATE_TOKEN	(WM_USER + 103)